config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('dispatches.urls', namespace='dispatches')),
]

dispatches/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path

from dispatches.apps import DispatchesConfig
from dispatches.views import base, home

app_name = DispatchesConfig.name

urlpatterns = [
    path('', base, name='base'),
    path('home/', home, name='home')
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

dispatches/models.py
from django.db import models

dispatches/views.py
from django.shortcuts import render


def base(request):
    return render(request, 'dispatches/base.html')


def home(request):
    return render(request, 'dispatches/home.html')

dispatches/templates/dispatches/base.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>Cover Template for Bootstrap</title>


    <!-- Bootstrap core CSS -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="{% static 'css/cover.css' %}" rel="stylesheet">
</head>

<body class="text-center">

<div class="cover-container d-flex h-100 p-3 mx-auto flex-column">
    <header class="masthead mb-auto">
        <div class="inner">
            <h3 class="masthead-brand">Menu</h3>
            <nav class="nav nav-masthead justify-content-center">
                <a href="{% url 'dispatches:home' %}" class="nav-link">Home</a>
                <a class="nav-link" href="#">Contact</a>
            </nav>
        </div>
    </header>

    <main role="main" class="inner cover">
        <h1 class="cover-heading">Cover your page.</h1>
        <p class="lead">Cover is a one-page template for building simple and beautiful home pages. Download, edit the text, and add your own fullscreen background photo to make it your own.</p>
        <p class="lead">
            <a href="#" class="btn btn-lg btn-secondary">Learn more</a>
        </p>
    </main>

    <footer class="mastfoot mt-auto">
        <div class="inner">
            <p>by <a href="https://vk.com/istheim">@istheim</a>.</p>
        </div>
    </footer>
</div>


<!-- Bootstrap core JavaScript
================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="{% static 'js/vendor/popper.min.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
</body>
</html>

dispatches/templates/dispatches/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Домашняя страница</title>
</head>
<body>

</body>
</html>